### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by V10lator** [jabelar/MovingLightSource-1.12#13]
```
[14:38:20] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$WorldTickEvent@7352c91d:
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[?:1.8.0_181]
        at java.util.ArrayList$Itr.next(ArrayList.java:859) ~[?:1.8.0_181]
        at com.blogspot.jabelarminecraft.movinglightsource.EventHandler.processLightPlacementForEntities(EventHandler.java:72) ~[EventHandler.class:?]
        at com.blogspot.jabelarminecraft.movinglightsource.EventHandler.onEvent(EventHandler.java:66) ~[EventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_284_EventHandler_onEvent_WorldTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:287) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:752) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[14:38:20] [Server thread/ERROR] [FML]: Index: 11 Listeners:
[14:38:20] [Server thread/ERROR] [FML]: 0: NORMAL
[14:38:20] [Server thread/ERROR] [FML]: 1: ASM: class com.endertech.minecraft.forge.world.ForgeWorld$WorldData onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[14:38:20] [Server thread/ERROR] [FML]: 2: ASM: class com.endertech.minecraft.mods.adchimneys.world.Events onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[14:38:20] [Server thread/ERROR] [FML]: 3: ASM: com.ferreusveritas.dynamictrees.event.CommonEventHandler@62a1c353 onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[14:38:20] [Server thread/ERROR] [FML]: 4: ASM: mods.railcraft.common.blocks.charge.ChargeManager@27c35449 tick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[14:38:20] [Server thread/ERROR] [FML]: 5: ASM: mods.railcraft.common.blocks.machine.wayobjects.signals.TokenManager@7e6e07e7 tick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[14:38:20] [Server thread/ERROR] [FML]: 6: ASM: sereneseasons.handler.season.SeasonHandler@202254dc onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[14:38:20] [Server thread/ERROR] [FML]: 7: ASM: sereneseasons.handler.season.RandomUpdateHandler@189215bd onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[14:38:20] [Server thread/ERROR] [FML]: 8: ASM: sereneseasons.handler.season.SeasonSleepHandler@5946912a onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[14:38:20] [Server thread/ERROR] [FML]: 9: ASM: sereneseasons.handler.season.WeatherFrequencyHandler@4a160815 onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[14:38:20] [Server thread/ERROR] [FML]: 10: ASM: drzhark.customspawner.handlers.SpawnTickHandler@786918a6 worldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[14:38:20] [Server thread/ERROR] [FML]: 11: ASM: com.blogspot.jabelarminecraft.movinglightsource.EventHandler@4a6315cd onEvent(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[14:38:20] [Server thread/ERROR] [FML]: 12: ASM: codechicken.nei.ServerHandler@3b4c7926 tickEvent(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[14:38:20] [Server thread/ERROR] [FML]: 13: ASM: class brightspark.sparkshammers.handlers.BlockEventHandler onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[14:38:20] [Server thread/ERROR] [FML]: 14: ASM: com.sk89q.worldedit.forge.ThreadSafeCache@1cf735fd tickStart(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[14:38:20] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[?:1.8.0_181]
        at java.util.ArrayList$Itr.next(ArrayList.java:859) ~[?:1.8.0_181]
        at com.blogspot.jabelarminecraft.movinglightsource.EventHandler.processLightPlacementForEntities(EventHandler.java:72) ~[EventHandler.class:?]
        at com.blogspot.jabelarminecraft.movinglightsource.EventHandler.onEvent(EventHandler.java:66) ~[EventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_284_EventHandler_onEvent_WorldTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:287) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:752) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[14:38:20] [Server thread/WARN] [org.dimdev.utils.ModIdentifier]: Failed to identify net.minecraftforge.fml.common.eventhandler.ASMEventHandler_284_EventHandler_onEvent_WorldTickEvent (untransformed name: net.minecraftforge.fml.common.eventhandler.ASMEventHandler_284_EventHandler_onEvent_WorldTickEvent)
[14:38:20] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: /home/libre/forge-server-1.12.2/./crash-reports/crash-2018-10-28_14.38.20-server.txt
[14:38:20] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
```

**Comment by V10lator** [comment]
Changing com.blogspot.jabelarminecraft.movinglightsource.EventHandler:72 to`for (Entity theEntity : Collections.unmodifiableList(theWorld.loadedEntityList))` seems to fix this. :) Please note however that this is quick&dirty + not 100% sure if really fixed.

**Comment by jabelar** [comment]
Yeah, that's probably fix.

Interesting people got this error as I tested over 5 hours and didn't see it, plus I'm not actually modifying the list while I'm iterating it (usual cause of concurrent modification errors) but I guess another thread is doing something at same time.

I'll post fix shortly.

**Comment by jabelar** [comment]
Okay, version 1.0.14 should be on CurseForge soon (submitted, just waiting for approval).

**Comment by V10lator** [comment]
Thanks but the fix doesn't seem to work (the collectable still uses the very same ArrayList as backend. This was a oversight on my end but as I said: It was quick&dirty). A working fix would be to copy the list, like `for (Entity theEntity : new ArrayList<Entity>(theWorld.loadedEntityList))` but that has a big performance impact. I'm sure if we would knew the real root of this there would be a better fix.

> I'm not actually modifying the list while I'm iterating it

For me it looks like you're right on this but the bug says otherwise. Maybe it's some NMS call which modifies the list but only under none-default cirumstances.

**Comment by jabelar** [comment]
I think this problem didn't happen in my earlier versions where I did use a copy but those did have some performance complaints. 

However, in my past versions I was copying several times (and filtering by different predicates).For a quick fix, I guess I'll "split the difference" and copy once per tick using the built in World#getEntities() method.

I think maybe the best fix is to handle the EntityJoinedWorldEvent and maintain my own list. It looks like the loadedEntityList is maintained right where that event fires.

**Comment by jabelar** [comment]
What's annoying is I don't get any concurrent modification errors in any case, so it is hard for me to test whether I'm fixing the problem...but I do know that working directly from the list can cause trouble.

**Comment by jabelar** [comment]
Okay, I issued 1.0.15. It uses a copy (same as I did originally) so some performance impact will return, but hopefully crashes solved. Please confirm if you've got time (I appreciate the feedback).

**Comment by V10lator** [comment]
> What's annoying is I don't get any concurrent modification errors in any case, so it is hard for me to test whether I'm fixing the problem

Maybe it's a compatibility issue with another mod? Here what's running on the server:
```
libre@libre-computer:~$ ls forge-server-1.12.2/mods/
1.12.2                                         VanillaFix-1.0.9-97.jar
AIImprovements-1.12.1-0.0.1b1.jar              Wawla-1.12.2-2.5.259.jar
AdChimneys-1.12.2-3.3.12.0-build.0197.jar      WearableBackpacks-1.12.2-3.1.3.jar
BetterFps-1.4.8.jar                            Weee!+Flowers+1.12.2b.jar
BiomesOPlenty-1.12.2-7.0.1.2399-universal.jar  aether_legacy-1.12.2-v3.2.jar
CodeChickenLib-1.12.2-3.2.2.353-universal.jar  bedrockbreaks-1.0.1.jar
CustomMobSpawner-3.11.4.jar                    bookworm+-+1.0.0+(1.12.2).jar
Dimensional mode-2.1.jar                       coherent_villages_beta_v1.4.10.jar
DrZharks MoCreatures Mod-12.0.5.jar            deuf-1.1-1.12.2.jar
DynamicTrees-1.12.2-0.8.2.jar                  foamfix-0.10.1-1.12.2.jar
DynamicTreesBOP-1.12.2-1.3.2.jar               furniture-5.15.0-1.12.2.jar
EndReset-0.9.1.jar                             hempfarmer-0.0.1.jar
ForgeEndertech-1.12.2-4.4.0.0-build.0180.jar   hopperducts-mc1.12-1.5.jar
GraveStone-1.12.2-Graves-1.2.0.jar             jei_1.12.2-4.12.1.217.jar
HardcoreDarkness-MC1.12.2-2.0.jar              kjlib-1.0.4.jar
Hwyla-1.8.26-B41_1.12.2.jar                    lib24time-1.0.jar
LagGoggles-FORGE-1.12.2-4.1.jar                lostcities-1.12-2.0.10.jar
MetalChests-v3.8.1.gfd0d85a.jar                moon-core+7.0+(1.12).jar
NoMobSpawningOnTrees-1.2.2-mc1.12.2.jar        movinglightsource-1.12.2-1.0.14.jar
NotEnoughItems-1.12.2-2.4.2.240-universal.jar  nanfix-final-absorbtion.jar
ObsidianAPI-1.0.0.jar                          obfuscate-0.2.6-1.12.2.jar
Pam's+HarvestCraft+1.12.2z.jar                 randompatches-1.12.2-1.6.1.0.jar
Placebo-1.12.2-1.4.1.jar                       redstonepaste-mc1.12-1.7.5.jar
Prehistoric+Eclipsev0.6-BETA.jar               simpleportals-1.12.2-1.5.1.0.jar
Railcraft_1.12.2-10.4.0-beta-1-unofficial.jar  sparkshammers-1.12.2-1.9.2.jar
SereneSeasons-1.12.2-1.2.6.null-universal.jar  stonechests-1.0.0.jar
SimpleDimensions-MC1.12-1.3.1-patched.jar      vehicle-mod-0.28.0-1.12.2.jar
SophisticatedWolves-1.12.2-3.13.7.jar          worldedit-forge-mc1.12-6.1.8-dist.jar
ThirstyBottles-1.12.2-1.1.4.jar                zawa+-+1.4.0+(1.12.2).jar
V10verlap-4.9.0.jar
```

> It uses a copy (same as I did originally) so some performance impact will return

I rember a similar problem in one of my mods. The solution was to have my own list, instantiated on mod loading. Then check what should happen and save it in the list in the iterating loop... After that loop over the list and do the work there, then clear() the list... Maybe something similiar could work here, too?

> Okay, I issued 1.0.15

Great, downloading it right now. :)

**Comment by V10lator** [comment]
The performance of the fix looks good, JProfiler can't even measure it:
![image](https://user-images.githubusercontent.com/1312422/47668337-75137c00-dba8-11e8-9c84-afc22d9a2dd3.png)

Will close this for now and re-open if the issue reappears. :)
