### ISSUE TITLE
minecraft server getting close..

### ISSUE THREAD

**Issue by pudimbrk** [jabelar/MovingLightSource-1.12#28]
[Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$WorldTickEvent@1c7f2fa3:
java.util.ConcurrentModificationException: null

**Comment by pudimbrk** [comment]
[19:30:08] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$WorldTickEvent@1c7f2fa3:
java.util.ConcurrentModificationException: null
        at java.util.IdentityHashMap$IdentityHashMapIterator.nextIndex(Unknown Source) ~[?:1.8.0_211]
        at java.util.IdentityHashMap$KeyIterator.next(Unknown Source) ~[?:1.8.0_211]
        at aroma1997.tatw.ic2usesfe.block.ICSourceEventListener.tick(ICSourceEventListener.java:76) ~[ICSourceEventListener.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1525_ICSourceEventListener_tick_WorldTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:287) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:752) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
[19:30:08] [Server thread/ERROR] [FML]: Index: 26 Listeners:
[19:30:08] [Server thread/ERROR] [FML]: 0: NORMAL
[19:30:08] [Server thread/ERROR] [FML]: 1: ASM: class thaumcraft.common.lib.events.ServerEvents worldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[19:30:08] [Server thread/ERROR] [FML]: 2: ASM: class WayofTime.bloodmagic.util.handler.event.WillHandler onServerWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[19:30:08] [Server thread/ERROR] [FML]: 3: ASM: class crazypants.enderio.base.material.material.MaterialCraftingHandler onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[19:30:08] [Server thread/ERROR] [FML]: 4: ASM: INSTANCE onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[19:30:08] [Server thread/ERROR] [FML]: 5: ASM: it.zerono.mods.zerocore.internal.common.MultiblockEventHandler@da66ac9 onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[19:30:08] [Server thread/ERROR] [FML]: 6: ASM: ic2.core.TickHandler@2b1f6aac onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[19:30:08] [Server thread/ERROR] [FML]: 7: ASM: ic2.core.energy.grid.EventHandler@73a8c6c5 onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[19:30:08] [Server thread/ERROR] [FML]: 8: ASM: INSTANCE onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[19:30:08] [Server thread/ERROR] [FML]: 9: ASM: DISTRIBUTION tick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[19:30:08] [Server thread/ERROR] [FML]: 10: ASM: mods.railcraft.common.blocks.machine.wayobjects.signals.TokenManager@1eace043 tick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[19:30:08] [Server thread/ERROR] [FML]: 11: ASM: mods.railcraft.common.carts.Train$1@2291e7f tick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[19:30:08] [Server thread/ERROR] [FML]: 12: ASM: vazkii.quark.tweaks.feature.ImprovedSleeping@47bc981 onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[19:30:08] [Server thread/ERROR] [FML]: 13: ASM: vazkii.quark.automation.feature.PistonsMoveTEs@5b1bf04e onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[19:30:08] [Server thread/ERROR] [FML]: 14: ASM: teamroots.embers.EventManager@516b3122 onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[19:30:08] [Server thread/ERROR] [FML]: 15: ASM: teamroots.embers.EventManager@516b3122 onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[19:30:08] [Server thread/ERROR] [FML]: 16: ASM: cofh.thermaldynamics.util.TickHandler@1e7a5579 tick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[19:30:08] [Server thread/ERROR] [FML]: 17: ASM: blusunrize.immersiveengineering.common.world.IEWorldGen@12022755 serverWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[19:30:08] [Server thread/ERROR] [FML]: 18: ASM: blusunrize.immersiveengineering.common.EventHandler@302655d4 onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[19:30:08] [Server thread/ERROR] [FML]: 19: ASM: hellfirepvp.astralsorcery.common.auxiliary.tick.TickManager@41b7aa4 worldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[19:30:08] [Server thread/ERROR] [FML]: 20: ASM: codechicken.chunkloader.handler.ChunkLoaderEventHandler@2f6b1ca6 worldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[19:30:08] [Server thread/ERROR] [FML]: 21: ASM: drzhark.customspawner.handlers.SpawnTickHandler@1b45959b worldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[19:30:08] [Server thread/ERROR] [FML]: 22: ASM: com.brandon3055.draconicevolution.world.WorldTickHandler@21a561c tickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[19:30:08] [Server thread/ERROR] [FML]: 23: ASM: mekanism.common.CommonWorldTickHandler@7a9fccba onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[19:30:08] [Server thread/ERROR] [FML]: 24: ASM: erogenousbeef.bigreactors.common.BigReactorsTickHandler@62eb24f2 onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[19:30:08] [Server thread/ERROR] [FML]: 25: ASM: crimson_twilight.immersive_energy.common.world.IEnWorldGen@176c91c9 serverWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[19:30:08] [Server thread/ERROR] [FML]: 26: ASM: aroma1997.tatw.ic2usesfe.block.ICSourceEventListener@47053f35 tick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[19:30:08] [Server thread/ERROR] [FML]: 27: ASM: aroma1997.core.util.registry.TickRegistry$1@3bdb4f7 worldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[19:30:08] [Server thread/ERROR] [FML]: 28: ASM: class teamroots.embers.util.OreTransmutationUtil onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[19:30:08] [Server thread/ERROR] [FML]: 29: ASM: codechicken.lib.world.WorldExtensionManager$WorldExtensionEventHandler@2eb74c98 serverTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[19:30:08] [Server thread/ERROR] [FML]: 30: ASM: levelup2.skills.crafting.FurnaceEfficiencyBonus@34e561dd doFurnaceTicks(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[19:30:08] [Server thread/ERROR] [FML]: 31: ASM: appeng.hooks.TickHandler@289960aa onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[19:30:08] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.util.ConcurrentModificationException: null
        at java.util.IdentityHashMap$IdentityHashMapIterator.nextIndex(Unknown Source) ~[?:1.8.0_211]
        at java.util.IdentityHashMap$KeyIterator.next(Unknown Source) ~[?:1.8.0_211]
        at aroma1997.tatw.ic2usesfe.block.ICSourceEventListener.tick(ICSourceEventListener.java:76) ~[ICSourceEventListener.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1525_ICSourceEventListener_tick_WorldTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:287) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:752) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
[19:30:08] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: C:\Users\mathe\Desktop\Servidor\.\crash-reports\crash-2020-04-06_19.30.08-server.txt

**Comment by pudimbrk** [comment]
it happens every time i try to conect wind generator (mekanisms) on energy..

if i say any wrong word, im sorry. But i gonna do my best to translate.
